### ISSUE TITLE
Windows: Need OpenSSL in libpack

### ISSUE THREAD

**Issue by luzpaz** [CADCloud/CADCloud#10]
@vejmarie please respond to https://forum.freecadweb.org/viewtopic.php?f=4&t=42945&p=372767#p372767

**Comment by vejmarie** [comment]
Just made it ;) Thanks for your help !

**Comment by apeltauer** [comment]
A compiled curl version for windows can be found here
[https://github.com/apeltauer/FreeCAD/releases/tag/openssl](url)
Add the content of Curl.7z to your windows libpack. Also check out the cmake modifications for the cloud workbench.

**Comment by vejmarie** [comment]
Can you propose it as a general candidate to build FreeCAD on windows ?

**Comment by apeltauer** [comment]
for sure, i also try to build curl in debug mode. when  this is done, i will make a whole libpack containing all...

**Comment by vejmarie** [comment]
I think this has been fix, everybody agrees to close that ?

**Comment by vejmarie** [comment]
I am closing this issue this has been Fixed in FreeCAD upstream. Thanks to @apeltauer
