### ISSUE TITLE
Cant see the bottom of the page with Chrom on Windows 10

### ISSUE THREAD

**Issue by apeltauer** [CADCloud/CADCloud#14]
Cant go to the bottom of the page when using Chrome on Windows 10.
So the user cant see the options and rev versions...

**Comment by vejmarie** [comment]
Can you post a link to a screenshot ? I am not sure to fully understand where the issue stand

**Comment by vejmarie** [comment]
@apeltauer I think I have reproduced the issue. I will have a look to it.
