### ISSUE TITLE
Model not created

### ISSUE THREAD

**Issue by sliptonic** [CADCloud/CADCloud#2]
I built FreeCAD with the cloud workbench enabled.  I can switch to the cloud wb though no new tools are shown.  Is that normal?

I opened an existing project file and executed the following code in the python console.  The last line took a minute or so to execute and returned without error.   I find nothing in my account on the website.  

It's not clear from either the web or from FreeCAD what went wrong.

```
import Cloud
Cloud.cloudurl(u"https://justyour.parts")
Cloud.cloudtcpport(u"443")
Cloud.cloudaccesskey(u"<my TokenAuth")
Cloud.cloudsecretkey(u"<my TokenSecret>")
Cloud.cloudsave(u"torsionspring")
```

**Comment by vejmarie** [comment]
Can you check if you have error message like this in your FreeCAD console ? (the shell from which you launch FreeCAD)

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidAccessKeyId</Code><Message>The access key ID you provided does not exist in our records.</Message><Key>Document.xml</Key><BucketName>torsionspring</BucketName><Resource>/torsionspring/Document.xml</Resource><Region>us</Region><RequestId>15F57CADEF49A88C</RequestId><HostId>7bb1b7e5-6e02-4373-a2d4-2f773c740dad</HostId></Error><?xml version="1.0" encoding="UTF-8"?>

**Comment by vejmarie** [comment]
There is something weird somewhere. I need to check that. I restarted the daemon and it looks like to work now. I have created successfully your model using your credential on the platform. I think when I first start the minio daemon the cache is not properly setup and denied proper auth. I have to investigate that.

**Comment by vejmarie** [comment]
can you retry now to check that you can create model from your FreeCAD build ?

**Comment by sliptonic** [comment]
Yes.  Seems to work now.  I created a new model with a nested Part and it looks good.  Interesting that the meshed version of the torsion spring doesn't render correctly.

**Comment by vejmarie** [comment]
That shall be fixed with the latest PR, I just integrated upstream. So if you want give it a try with your local Docker build which has also been introduced into the latest PR, that will be great !
