### ISSUE TITLE
website improvement:  Eliminate/reduce splash after login.

### ISSUE THREAD

**Issue by sliptonic** [CADCloud/CADCloud#49]
I'm on a large landscape format monitor 1280x1024.  Even so, after logging in, all the public projects are below the scroll line.

A new user arriving will not see that there are projects to explore.  Even after logging in, you have to scroll before you see anything of interest.

Maybe replace the static image with a rotator of 'featured projects, or simply collapse it so the public projects are the main focus of the screen.

**Comment by vejmarie** [comment]
Yes I agree, that is an issue that we have to address.
