### ISSUE TITLE
website improvement:   Expose sharable links for public projects.

### ISSUE THREAD

**Issue by sliptonic** [CADCloud/CADCloud#50]
The direct link to a project is only visible to the project owner.  Public projects should have their public links exposed so anyone can share it.

**Comment by vejmarie** [comment]
I am working on it. Shall be done by the end of the week. I am looking for a nice icon to put into the preview cards !

**Comment by sliptonic** [comment]
I would use something standard from the bootstrap or glyphicon sets or another off the shelf icon so it's recognizable.

https://www.google.com/search?q=share+icon&sxsrf=ALeKk02UNjKekIEnf1tX0nJIKGhaJCOL9w:1588527052447&tbm=isch&source=iu&ictx=1&fir=6AK0jO9vWyTpxM%253A%252CGZ-S1TT4MhSMpM%252C%252Fm%252F0gvr2x0&vet=1&usg=AI4_-kR3zHDrxNksafS-vSnTL-LmmmWMAw&sa=X&ved=2ahUKEwiF2bS1nJjpAhVUCs0KHaQQBr0Q_B0wE3oECAwQAw#imgrc=6AK0jO9vWyTpxM:

**Comment by vejmarie** [comment]
#57 is adding this feature. It is not yet "perfect" but that is a beginning. I will integrate it upstream, and will probably close the request. Let me know your thought on how to improve by reopening a new request !
